# Generated by Django 3.2.6 on 2021-08-21 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(default=0, help_text='указать сумму в долларах', verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=datetime.date.today, verbose_name='Премьера в мире'),
        ),
    ]
