# Generated by Django 3.2.6 on 2021-08-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_world_premiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(verbose_name='Премьера в мире'),
        ),
    ]
