# Generated by Django 3.2.6 on 2021-08-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_world_premiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='world_premiere',
        ),
    ]
